# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  NugetApiKey:
    secure: fgX/jrPnACf6a2RQgQcCEVovNM0PoAD6F2FwQshVMiKCKhWtivvQtl4uf5JsKVzf

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

install:
  - cinst -y pester
  - ps: Get-PackageProvider -Name NuGet -Force

# branches to build
branches:
  # whitelist
  only:
    - master

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: .\Build\Invoke-Build.ps1 -File .\Build\.build.ps1